### ISSUE TITLE
Require a minimum return amount

### ISSUE THREAD

**Issue by sembrestels** [CommonsSwarm/tec-convert#10]
When we are using [makeBuyOrder](https://github.com/TECommons/tec-convert/blob/e836ac7f8cccb7fc13de3323699e51e501606d77/lib/web3-contracts.js#L244) and [makeSellOrder](https://github.com/TECommons/tec-convert/blob/e836ac7f8cccb7fc13de3323699e51e501606d77/lib/web3-contracts.js#L248) we are not requiring a `_minReturnAmountAfterFee`, see [[1]](https://github.com/1Hive/marketplace-app/blob/master/apps/bancor-market-maker/contracts/BancorMarketMaker.sol#L237) and [[2]](https://github.com/1Hive/marketplace-app/blob/master/apps/bancor-market-maker/contracts/BancorMarketMaker.sol#L334) respectively.

We may want to set it up with an allowed slippage of -1%. For this we need to complete first #4, to know in the frontend which are the entry and exit tributes.

The **minimum received** should appear in the interface as well. It can appear below `The conversion amount is an estimate`, take inspiration from uniswap/honeyswap:
![Screenshot from 2020-11-28 23-07-08](https://user-images.githubusercontent.com/931684/100527096-8425e780-31cf-11eb-9b2a-8cace9ec4f72.png)

**Comment by GriffGreen** [comment]
add a slippage maximum into the front end, in the code there is a function that has a minimum... it defaults to 0 but we want a default of 1% as the first step, and then we can give the user the view that it is 1%

That is enough for now... the next step is to make it customizable after that.
