### ISSUE TITLE
Support Network API

### ISSUE THREAD

**Issue by sembrestels** [CommonsSwarm/tec-convert#20]
Do what was done in the hatch... if you are on the wrong network, alert the user!

We can reuse the work in the Hatch Front End

**Comment by GriffGreen** [comment]
Pavl is working on a loading screen when you change networks for the Hatch... we might need to change the styles....

**Comment by marthendalnunes** [comment]
![image](https://user-images.githubusercontent.com/18421017/121349054-7a5c0a00-c8ff-11eb-8607-d8daf4af8f88.png)
change to metamask pop up 'do you want to connect w/ xDai'
