### ISSUE TITLE
Manage exit tribute properly

### ISSUE THREAD

**Issue by sembrestels** [CommonsSwarm/tec-convert#4]
The tribute is not applied in the frontend conversion and can mislead on how much collateral you are going to receive when selling bonded tokens.

The `entry tribute` and `exit tribute` should appear just below `The conversion amount is an estimate`, you can take inspiration from uniswap/honeyswap's liquidity provider fee:

![Screenshot from 2020-11-28 23-07-08](https://user-images.githubusercontent.com/931684/100527026-e7fbe080-31ce-11eb-9bd1-146ed482fdd8.png)

**Comment by GriffGreen** [comment]
you should see how much you get, the exit tribute currently goes to the funding pool so the front end says you get 100... but really you get 80 and 20 goes to the funding pool!

**Comment by fioreb** [comment]
Here you can find the design for this:
https://www.figma.com/file/3qP2tcfrhZegRQD9aFLOQe/Convert?node-id=3%3A551

**Comment by Harthor** [comment]
working on this notion doc https://www.notion.so/sha256/https-github-com-TECommons-tec-convert-issues-4-19501b281b6e437f9fd48f79c6bd1f0c
